[package]
name = "identity-iota"
version = "0.2.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "An IOTA Tangle intergration for the identity-rs library."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
async-trait = { version = "0.1", default-features = false }
futures = { version = "0.3" }
identity-core = { version = "=0.2.0", path = "../identity-core" }
identity-credential = { version = "=0.2.0", path = "../identity-credential" }
identity-did = { version = "=0.2.0", path = "../identity-did" }
iota-constants = { version = "0.2", default-features = false }
iota-conversion = { version = "0.5", default-features = false }
#iota-core = { git = "https://github.com/Thoralf-M/iota.rs", rev = "d7c8c64fc3ac2340f0148708a916c245f42fd454" }
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "86f5bb24727266e13abd772616d0700abe866892" }
# iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "c993159e2a0d4eb250dc82e43e233219144e5931" }
lazy_static = { version = "1.4", default-features = false }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
thiserror = { version = "1.0", default-features = false }

[dependencies.iota-crypto]
git = "https://github.com/iotaledger/crypto.rs"
rev = "c3bf565eba62d0b81144174c2ff917bfde282e49"
default-features = false
features = ["blake2b"]
